##
# @file    azure-pipelines.yml
# @author  dragon-archer (dragon-archer@outlook.com)
# @brief   The Azure Pipelines configure file
# @version 0.0.1
#
# @license This file is published under The MIT License
#          See License in the root directory for details
#          Copyright (c) 2020 dragon-archer
#

trigger:
- master
- develop

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      generator: 'Unix Makefiles'
      extra: ' '
      sudo: 'sudo'
    windows:
      imageName: 'windows-latest'
      generator: 'Visual Studio 16 2019'
      extra: '-A x64'
      sudo: ' '

pool:
  vmImage: $(imageName)

steps:
- script: |
    mkdir build && cd build
    cmake .. -G "$(generator)" $(extra)
  displayName: Configure project by CMake
- script: |
    cmake --build build --config Debug
  displayName: Build project in Debug mode
- script: |
    cmake --build build --config Release
  displayName: Build project in Release mode
- script: |
    $(sudo) cmake --install build --config Release
  displayName: Install project in Release mode
- script: |
    cpack -G TGZ -C Release --config build/CPackConfig.cmake 
  displayName: Pack binaries in Release mode by CPack
- script: |
    cpack -G TGZ --config build/CPackSourceConfig.cmake 
  displayName: Pack source by CPack