##
# @file    .github/workflows/build.yml
# @author  dragon-archer (dragon-archer@outlook.com)
# @brief   The GitHub Actions configure file
# @version 0.0.1
#
# @license This file is published under The MIT License
#          See License in the root directory for details
#          Copyright (c) 2020 dragon-archer
#

name: CI Build

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    braches:
    - master
    - develop


jobs:
  Build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
        - os: windows-latest
          generator: 'Visual Studio 16 2019'
          extra: '-A x64'
          sudo: ' '
          removeChoco: 'rm ${env:ChocolateyInstall}\bin\cpack.exe'
        - os: ubuntu-latest
          generator: 'Unix Makefiles'
          extra: ' '
          sudo: 'sudo'
          removeChoco: 'true'
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure project by CMake
      run: |
        mkdir build && cd build
        cmake .. -G "${{ matrix.generator }}" ${{ matrix.extra }}
    - name: Build project in Debug mode
      run: |
        cmake --build build --config Debug
    - name: Build project in Release mode
      run: |
        cmake --build build --config Release
    - name: Install the project in Release mode
      run: |
        ${{ matrix.sudo }} cmake --install build --config Release
    - name: Pack binaries in Release mode by CPack
      run: |
        ${{ matrix.removeChoco }} && ${{ matrix.sudo }} cpack -G TGZ -C Release --config build/CPackConfig.cmake
    - name: Pack source by CPack
      run: |
        ${{ matrix.sudo }} cpack -G TGZ --config build/CPackSourceConfig.cmake 
